services:
  experiments:
    # command: nvidia-smi
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 2 # gpu numbers
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all

  api:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 2
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all