FROM node:22-alpine

WORKDIR /app/server

# Copia i file di dipendenze
COPY server/package*.json ./

# Installa le dipendenze
RUN npm install --production

# Copia il codice sorgente del server
COPY server/src ./src

# Espone la porta del server
EXPOSE 3001

# Avvia il server
CMD ["npm", "start"]
